### ISSUE TITLE
Can't use it in Discord Bot

### ISSUE THREAD

**Issue by ghost** [GrandMoff100/DiscordGame#4]
Im unable to use the examples in my bot 
Can u show an example??
like in this structure>>>
```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix='>')

@bot.command()
async def ping(ctx):
    await ctx.send('pong')

bot.run('token')```

**Comment by GrandMoff100** [comment]
DiscordGame is not meant to do this.

DiscordGame abstracts the `commands.Bot` class and makes its own bot. This library is not meant to integrate with another discord bot as doing so would break certain internal mechanics. 

In the future, the framework might be able to expose its internal bot for extensional use, but currently, your query is not supported.

**Comment by ghost** [comment]
But how to trigger the games ? What's the command for that?

**Comment by GrandMoff100** [comment]
I apologize that it is not clear in the README

But in examples/example.py, it imports and runs the games from the other two files in the examples directory.

```py
from discordgame import GameHost

# Import our example games from 2 other files.
from .snake import Snake
from .madlib import MadLib

host = GameHost('*')

# Add our Games to the GameHost so users can play them.
host.add_game(Snake)
host.add_game(MadLib)

# Add run the GameHost.
host.run(TOKEN)
```

**Comment by ghost** [comment]
Thankss

**Comment by GrandMoff100** [comment]
You are very welcome!
